Traceback (most recent call last):
  File "/home/pfcf/pfcfProject/OI/UpdateOI_MySQL.py", line 19, in <module>
    from mpl_finance import candlestick_ohlc
ModuleNotFoundError: No module named 'mpl_finance'
2021-01-18 06:15:02.407679
20210118
2021-01-20
202101
Traceback (most recent call last):
  File "/home/pfcf/pfcfProject/OI/UpdateOI_MySQL.py", line 92, in <module>
    lower=math.floor(generator_df.iloc[0][0]/100-9)*100
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1767, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 2137, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 2062, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
2021-01-18 06:16:02.919735
20210118
2021-01-20
202101
Traceback (most recent call last):
  File "/home/pfcf/pfcfProject/OI/UpdateOI_MySQL.py", line 92, in <module>
    lower=math.floor(generator_df.iloc[0][0]/100-9)*100
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1767, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 2137, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 2062, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
2021-01-18 06:17:02.505921
20210118
2021-01-20
202101
Traceback (most recent call last):
  File "/home/pfcf/pfcfProject/OI/UpdateOI_MySQL.py", line 92, in <module>
    lower=math.floor(generator_df.iloc[0][0]/100-9)*100
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1767, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 2137, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 2062, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
2021-01-18 06:18:03.041731
20210118
2021-01-20
202101
Empty DataFrame
Columns: [Twseclose]
Index: []
Traceback (most recent call last):
  File "/home/pfcf/pfcfProject/OI/UpdateOI_MySQL.py", line 93, in <module>
    lower=math.floor(generator_df.iloc[0][0]/100-9)*100
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1767, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 2137, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 2062, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
2021-01-18 06:19:02.676361
20210118
2021-01-20
202101
Empty DataFrame
Columns: [Twseclose]
Index: []
Traceback (most recent call last):
  File "/home/pfcf/pfcfProject/OI/UpdateOI_MySQL.py", line 93, in <module>
    lower=math.floor(generator_df.iloc[0][0]/100-9)*100
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1767, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 2137, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/pfcf/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 2062, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
